-- =============================================================================
-- Car Rental & Fleet Booking System Database Schema (Supabase / PostgreSQL)
-- =============================================================================

-- Drop tables if needed during fresh setup (ordered by dependencies)
-- DROP TABLE IF EXISTS rentals CASCADE;
-- DROP TABLE IF EXISTS vehicles CASCADE;

-- 1. Vehicles Table
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    year INT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
    daily_rate NUMERIC(10, 2) NOT NULL CHECK (daily_rate > 0),
    fuel_type TEXT NOT NULL,
    seating_capacity INT NOT NULL DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'rented', 'maintenance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Rentals / Bookings Table
CREATE TABLE IF NOT EXISTS rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE RESTRICT,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_cost NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked', 'active', 'completed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_date_range CHECK (end_date >= start_date)
);

-- 3. Collision Check Index
-- Optimizes overlap queries for booked or active reservations on a specific vehicle
CREATE INDEX IF NOT EXISTS idx_rentals_vehicle_dates ON rentals (vehicle_id, start_date, end_date) 
    WHERE status IN ('booked', 'active');

-- 4. Reusable SQL Function for Vehicle Availability / Collision Check
-- Callable via supabase.rpc('check_vehicle_availability', { ... })
CREATE OR REPLACE FUNCTION check_vehicle_availability(
    p_vehicle_id BIGINT, 
    p_start_date DATE, 
    p_end_date DATE, 
    p_exclude_rental_id BIGINT DEFAULT NULL
) RETURNS BOOLEAN AS $$
DECLARE
    conflict_count INT;
BEGIN
    SELECT COUNT(*) INTO conflict_count
    FROM rentals
    WHERE vehicle_id = p_vehicle_id
      AND status IN ('booked', 'active')
      AND (p_exclude_rental_id IS NULL OR id != p_exclude_rental_id)
      AND start_date <= p_end_date
      AND end_date >= p_start_date;
    RETURN conflict_count = 0;
END;
$$ LANGUAGE plpgsql;
